name: hkcoin
description: "HKCoin Mobile App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.3
  dio: ^4.0.6
  dartz: ^0.10.1
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.3
  easy_localization: ^3.0.1
  toastification: ^2.3.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  dots_indicator: ^4.0.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16
  get: ^4.7.2
  flutter_spinkit: ^5.2.1
  html: ^0.15.6
  flutter_html: ^3.0.0
  signalr_netcore: ^1.4.3
  flutter_launcher_icons: ^0.14.3
  expandable: ^5.0.1
  dropdown_button2: ^2.3.9
  easy_localization_loader: ^2.0.2
  path_provider: ^2.1.5
  restart_app: ^1.3.2
  image: ^4.5.3
  camera: ^0.11.1
  flutter_animate: ^4.5.2
  timezone: ^0.10.1
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  dropdown_search: ^5.0.2

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  json_serializable:
  json_annotation:
  bloc_test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/hkc_logo_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "assets/icons/hkc_logo_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/icons/hkc_logo_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/icons/hkc_logo_icon.png"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true
    # flare_flutter: false
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter

    exclude:
      - .env.uat
      - .env.dev
      - .env.prod
      # - assets/images/chip3/chip3.jpg
      # - pictures/chip5.jpg
      # - assets/flare/

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

  colors:
    enabled: true
    outputs:
      class_name: AppColor
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    # - .env.uat
    # - .env.dev
    # - .env.prod
    - assets/
    - assets/images/
    - assets/translations/
    - assets/icons/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSans-Light.woff
          weight: 300
        - asset: assets/fonts/GoogleSans/GoogleSans-Regular.woff
          weight: 400
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.woff
          weight: 500
        - asset: assets/fonts/GoogleSans/GoogleSans-Bold.woff
          weight: 700
        - asset: assets/fonts/GoogleSans/GoogleSans-Black.woff
          weight: 800
