class Endpoints {
  static String login = "Customers/Login";
  static String register = "Customers/Register";
  static String logout = "Customers/Logout";
  static String getProduct = "Products";
  static String getProductDetail(int id) => "Products($id)";
  static String getOrders = "Customers/Orders";
  static String customerInfo = "Customers/Me/";
  static String getWalletInfo = "Wallets/Dashboard";
  static String getWalletBalances = "Wallets/Balances";
  static String getWalletHistories = "WalletHistories/Search";
  static String getCart = "ShoppingCartItems/GetCart";
  static String addToCart = "ShoppingCartItems/AddToCart";
  static String deleteCart = "ShoppingCartItems/DeleteCart";
  static String updateCartItem(int id) => "ShoppingCartItems($id)/UpdateItem";
  static String getNews = "NewsItems";
  static String getNewsDetail(int id) => "NewsItems($id)";
  static String changePassword = "Customers/ChangePassword";
  static String getSlides = "Sliders";
  static String getAddresses = "Customers/Addresses";
  static String getDownlines = "Customers/Downline";
  static String getProvinces({int countryCode = 230}) =>
      "Countries($countryCode)/StateProvinces";
  static String getCountry = "Countries";
  static String addAddress = "Orders/AddAddress";
  static String selectAddress = "Orders/SelectBillingAddress";
  static String checkout = "Orders/Checkout";
  static String checkoutComplete = "Orders/CheckoutComplate";
  static String selectPaymentMethod = "Orders/SelectPaymentMethod";
  static String orderTotal = "Orders/OrderTotal";
  static String getLanguage = "Languages/GetLanguage";
  static String getLanguages = "Languages";
  static String setLanguage = "Languages/SetLanguage";
  static String getWithDrawalsInvest = "WithDrawals/Invest";
  static String getWithDrawalsProfit = "WithDrawals/Profit";
  static String getWithDrawalsHistories = "WithDrawals/Search";
  static String getExchangePrice = "WithDrawals/ExchangePrice";
  static String getExchangePackage = "WithDrawals/ExchangePackage";
  static String kycInfo = "Customers/KYC";
  static String kycStatus = "Customers/KYCStatus";
  static String kycComplete = "Customers/KycComplate";
  static String kycValidate = "Customers/Validate";
}
